// Textos comunes a todas las prácticas, en español y en inglés. Los propios de
// cada práctica viven en su `textos.js` como { es, en }.

export const T = {
  es: {
    cargando: 'Cargando…',
    entrada_titulo: 'Escribe tu código',
    entrada_ayuda: 'Es el código de 4 caracteres que te ha dado tu profesor.',
    entrada_boton: 'Entrar',
    entrada_error: 'Ese código no es correcto. Revísalo: son 4 letras o números.',
    probar: 'Probar sin código',
    probar_aviso: 'Sin código puedes practicar, pero no se guarda nada.',
    menu_titulo: 'Ejercicios',
    menu_regla: (inicial, penalizacion, maximo = 40) => `En cada ejercicio tienes que acertar ${inicial} veces. ¡Ojo! Cada fallo añade ${penalizacion} más (hasta un máximo de ${maximo}). Piénsalo bien antes de contestar.`,
    menu_regla_varia: 'En cada ejercicio tienes que acertar un número de veces. ¡Ojo! Cada fallo añade alguna más. Piénsalo bien antes de contestar.',
    regla_fila: (inicial, penalizacion) => `${inicial} aciertos · cada fallo, +${penalizacion}`,
    animos: [
      '¡Ánimo! Lo importante es seguir intentándolo.',
      'No pasa nada: de los errores también se aprende.',
      'Casi. Lee la explicación y a por el siguiente.',
      'Con calma: esto cuesta al principio. ¡Tú puedes!',
    ],
    sin_codigo: 'Estás practicando sin código: no se guarda nada.',
    ejercicio: n => `Ejercicio ${n}`,
    empezar: 'Empezar',
    seguir: 'Seguir',
    repetir: 'Practicar otra vez',
    hecho: 'Hecho',
    quedan: n => `Te quedan ${n}`,
    fallos: n => (n === 1 ? '1 fallo' : `${n} fallos`),
    comprobar: 'Comprobar',
    siguiente: 'Siguiente',
    borrar: 'Borrar',
    si: 'Sí',
    no: 'No',
    verdadero: 'Verdadero',
    falso: 'Falso',
    salir: '← Ejercicios',
    todas: '← Todas las prácticas',
    bien: '¡Bien!',
    tambien: 'También vale:',
    mal: 'No es correcto.',
    penalizacion: n => (n > 0 ? `+${n} · ${n === 1 ? 'Se añade 1 más' : `Se añaden ${n} más`}.` : 'Ya tienes el máximo: no se añaden más.'),
    fijate: 'Fíjate:',
    por_eso: 'Por eso',
    por_ejemplo: 'Por ejemplo:',
    y: 'y',
    o: 'o',
    es: 'es',
    no_es: 'no es',
    resto: 'resto',
    error_item: 'Este ejercicio no se ha podido mostrar. No cuenta: pasa al siguiente.',
    fin_titulo: '¡Ejercicio terminado!',
    fin_resumen: (a, f) => `Aciertos: ${a} · Fallos: ${f}`,
    fin_practica: 'Era una repetición para practicar: tu resultado guardado no cambia.',
    resultado_titulo: 'Tu código de resultado',
    resultado_parcial: (n, total) => `Has terminado ${n} de ${total} ejercicios. Cuando los termines todos, envía este código a tu profesor.`,
    resultado_completo: total => `¡Has terminado los ${total} ejercicios! Copia este código y envíaselo a tu profesor.`,
    copiar: 'Copiar',
    copiado: '¡Copiado!',
    cambiar_codigo: 'Salir',
    // Portada
    portada_titulo: 'Prácticas de la unidad 2',
    portada_subtitulo: 'Divisibilidad',
    portada_ayuda: 'Elige una práctica. En todas entras con el mismo código.',
    portada_codigo: codigo => `Tu código: ${codigo}`,
    portada_hechos: (n, total) => `${n} de ${total} ejercicios`,
    portada_abrir: 'Abrir',
    portada_vacia: 'Todavía no hay prácticas publicadas.',
  },
  en: {
    cargando: 'Loading…',
    entrada_titulo: 'Type your code',
    entrada_ayuda: 'It is the 4-character code your teacher gave you.',
    entrada_boton: 'Enter',
    entrada_error: 'That code is not correct. Check it: it has 4 letters or numbers.',
    probar: 'Try without a code',
    probar_aviso: 'Without a code you can practise, but nothing is saved.',
    menu_titulo: 'Exercises',
    menu_regla: (inicial, penalizacion, maximo = 40) => `In each exercise you need ${inicial} correct answers. Careful! Each mistake adds ${penalizacion} more (up to a maximum of ${maximo}). Think carefully before you answer.`,
    menu_regla_varia: 'In each exercise you need a number of correct answers. Careful! Each mistake adds some more. Think carefully before you answer.',
    regla_fila: (inicial, penalizacion) => `${inicial} correct answers · each mistake, +${penalizacion}`,
    animos: [
      'Keep going! The important thing is to keep trying.',
      'No problem: we also learn from mistakes.',
      'Almost. Read the explanation and try the next one.',
      'Don’t worry, this is hard at first. You can do it!',
    ],
    sin_codigo: 'You are practising without a code: nothing is saved.',
    ejercicio: n => `Exercise ${n}`,
    empezar: 'Start',
    seguir: 'Continue',
    repetir: 'Practise again',
    hecho: 'Done',
    quedan: n => `${n} to go`,
    fallos: n => (n === 1 ? '1 mistake' : `${n} mistakes`),
    comprobar: 'Check',
    siguiente: 'Next',
    borrar: 'Clear',
    si: 'Yes',
    no: 'No',
    verdadero: 'True',
    falso: 'False',
    salir: '← Exercises',
    todas: '← All the practices',
    bien: 'Correct!',
    tambien: 'Also correct:',
    mal: 'That is not correct.',
    penalizacion: n => (n > 0 ? `+${n} · ${n === 1 ? '1 more is added' : `${n} more are added`}.` : 'You already have the maximum: no more are added.'),
    fijate: 'Look:',
    por_eso: 'So',
    por_ejemplo: 'For example:',
    y: 'and',
    o: 'or',
    es: 'is',
    no_es: 'is not',
    resto: 'remainder',
    error_item: 'This exercise could not be shown. It does not count: go to the next one.',
    fin_titulo: 'Exercise finished!',
    fin_resumen: (a, f) => `Correct: ${a} · Mistakes: ${f}`,
    fin_practica: 'This was extra practice: your saved result does not change.',
    resultado_titulo: 'Your result code',
    resultado_parcial: (n, total) => `You have finished ${n} of ${total} exercises. When you finish them all, send this code to your teacher.`,
    resultado_completo: total => `You have finished the ${total} exercises! Copy this code and send it to your teacher.`,
    copiar: 'Copy',
    copiado: 'Copied!',
    cambiar_codigo: 'Log out',
    // Portada
    portada_titulo: 'Unit 2 practices',
    portada_subtitulo: 'Divisibility',
    portada_ayuda: 'Choose a practice. You use the same code in all of them.',
    portada_codigo: codigo => `Your code: ${codigo}`,
    portada_hechos: (n, total) => `${n} of ${total} exercises`,
    portada_abrir: 'Open',
    portada_vacia: 'There are no practices yet.',
  },
};

// El botón que, tras responder, traduce el ítem al otro idioma: su texto va
// siempre en el idioma AL QUE se cambia (no en el del ítem actual).
export const TRADUCCION = { es: 'Ver en español', en: 'See in English' };

/** Une frases con «y» (o con «o»): «a, b y c». */
export function unir(frases, idioma, conjuncion = 'y') {
  if (frases.length < 2) return frases.join('');
  return `${frases.slice(0, -1).join(', ')} ${T[idioma][conjuncion]} ${frases.at(-1)}`;
}

/** Escapa un texto para meterlo en HTML. */
export function esc(texto) {
  return String(texto).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
